config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [:show, :index]
  resources :orders, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    Order.create(order_params)
    redirect_back(fallback_location: root_path)
  end

  private

  def order_params
    params.require(:order).permit(:quantity, :product_id, :comment, :name, :phone)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order = Order.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NazShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <%= link_to product.title, product_path(id: product.id) %>
  br
  <%= product.description %>
  hr
<% end %>

app/views/products/show.html.erb
<h2>
  <%= @product.title %>
</h2>
<p>
  <%= @product.description %>
</p>

Buy:
<%= simple_form_for @order do |f| %>
  <%= f.input :quantity %>
  <%= f.input :phone %>
  <%= f.input :name %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>